version: '3'
services:
  #-- PHP Service
  action_app:
    build:
      context: .
      dockerfile: docker/Dockerfile
    container_name: action_app
    restart: unless-stopped
    tty: true
    environment:
      SERVICE_TAGS: dev
    working_dir: /var/www
    volumes:
      - ./app/:/var/www
      - ./docker/php/local.ini:/usr/local/etc/php/conf.d/local.ini
    networks:
      - app-network
  #-- Nginx Service
  action_webserver:
    image: nginx:alpine
    container_name: action_webserver
    restart: unless-stopped
    tty: true
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./app/:/var/www
      - ./docker/nginx/conf.d:/etc/nginx/conf.d
    networks:
      - app-network

  #-- MySQL Service
  action_db:
    image: mysql:8
    container_name: action_db
    restart: unless-stopped
    tty: true
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: action
      MYSQL_ROOT_PASSWORD: dilJi0AR
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    volumes:
      - dbdata:/var/lib/mysql-files/
      - ./docker/mysql/my.cnf:/etc/mysql/my.cnf
    networks:
      - app-network

#-- Docker networks
networks:
  app-network:
    driver: bridge

#-- Volumes
volumes:
  dbdata:
    driver: local